apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
          requests:
            memory: "4096Mi"
            cpu: "4000m"
          limits:
            memory: "8192Mi"
            cpu: "8000m"