apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "250m"