apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
          requests:
            memory: "1024Mi"
            cpu: "2000m"
          limits:
            memory: "2048Mi"
            cpu: "4000m"