apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"