apiVersion: v1
kind: Namespace
metadata:
  name: $tenantId-frontend
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: $tenantId-frontend
spec:
  project: default
  source:
    repoURL: https://github.com/sam-andaluri/$repo.git
    targetRevision: HEAD
    path: tier
  destination:
    server: https://kubernetes.default.svc
    namespace: $tenantId-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true